spring.application.name=cinema-back

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_app
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI Properties
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operations-sorter=alpha


# ----------------------------------------------------
# JWT Security Configuration
# ----------------------------------------------------
# 256-bit Base64 Encoded Secret Key
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Access Token expiration (24 hours in milliseconds)
jwt.expiration=86400000
# Refresh Token expiration (7 days in milliseconds)
jwt.refresh-expiration=604800000

# ----------------------------------------------------
# Mail Settings (Gmail SMTP for OTP Emails)
# ----------------------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sinhporsurii@gmail.com
# Use an App Password generated from Google Account Security (NOT your normal Gmail password)
spring.mail.password=upyf gpck ztsv cgqc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ==========================================
# NBC BAKONG LIVE / SANDBOX CONFIGURATION
# ==========================================
bakong.merchant.account=011600961@aba
bakong.merchant.name=Cinema Project
bakong.merchant.city=PHNOM PENH
bakong.merchant.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiZGE0ZjkxZDVlMjk1NDkyNSJ9LCJpYXQiOjE3ODgyNzk1NzIsImV4cCI6MTc5NjA1NTU3Mn0.ub4qyMpmKGAUZP8B5iwCwZUUT9u0VBOHIhCCrNeSjlo


