spring.application.name=cinema-back

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_app
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI Properties
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operations-sorter=alpha


# ----------------------------------------------------
# JWT Security Configuration
# ----------------------------------------------------
# 256-bit Base64 Encoded Secret Key
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Access Token expiration (24 hours in milliseconds)
jwt.expiration=86400000
# Refresh Token expiration (7 days in milliseconds)
jwt.refresh-expiration=604800000

# ----------------------------------------------------
# Mail Settings (Gmail SMTP for OTP Emails)
# ----------------------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sinhporsurii@gmail.com
# Use an App Password generated from Google Account Security (NOT your normal Gmail password)
spring.mail.password=erng pgph vzyd wtec    
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# ==========================================
# NBC BAKONG LIVE / SANDBOX CONFIGURATION
# ==========================================
#bakong.merchant.account=011600961@aba
#bakong.merchant.name=Cinema Project
#bakong.merchant.city=PHNOM PENH
#bakong.merchant.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiZGE0ZjkxZDVlMjk1NDkyNSJ9LCJpYXQiOjE3ODgyNzk1NzIsImV4cCI6MTc5NjA1NTU3Mn0.ub4qyMpmKGAUZP8B5iwCwZUUT9u0VBOHIhCCrNeSjlo

# Increase maximum file size allowed for upload
spring.servlet.multipart.max-file-size=10MB

# Increase maximum overall request size (includes form data + files)
spring.servlet.multipart.max-request-size=10MB

# Telegram Bot Configuration
telegram.bot.token=8799132325:AAFjA08FBvlzPVesW450CDEeuPk2vxm_4Rs
telegram.bot.chat-id=7632041812

# Cloudinary Configuration
cloudinary.cloud-name=dppeuniv1
cloudinary.api_key=297117491985496
cloudinary.api_secret=7A-JIsvzssaLNLHcshVpbx4-NWM

# ==========================================
# Cloudflare Turnstile
# ==========================================
turnstile.verify-url=https://challenges.cloudflare.com/turnstile/v0/siteverify
turnstile.secret-key=0x4AAAAAAEpf848sYRwjtGfc8juoPfl712Y


# with keycloak
keycloak.issuer-uri=http://localhost:8081/realms/cinemax

# bakong here need to do
bakong.bearer.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiOWFiYmY2ODE3ZDEyNGExMiJ9LCJpYXQiOjE3ODk0Njc4MjUsImV4cCI6MTc5NzI0MzgyNX0.VH_alApUys_5Yi6BnrAP6WpL6WDfXNLzAXVJoEu2xmY
bakong.api.url=https://api-bakong.nbc.gov.kh/v1
bakong.account.id=sopha_khoeurn@bkrt
bakong.merchant.name=CinemaX
bakong.merchant.city=Phnom Penh

bakong.testing-mode=false

